# -*- coding: utf-8 -*-
"""ids561_assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QFLHUO7jePW72YsIlkacUcw2xaXiNK27
"""

import pandas as pd

# read the file without first row as header
def dataread():
  data=pd.read_csv('temperatures.txt', header=None)
  return data

df=dataread()
df.head()

# cleans the file and return cleaned file
def dataclean(data):
  # removing unwanted puntuations
  data=data.apply(lambda x: x.str.replace(')',''))
  data=data.apply(lambda x: x.str.replace('(',''))
  data=data.apply(lambda x: x.str.replace(' ',''))
  #splitting year and month and renaming column for temp
  data['year1'], data['month1'] = data[0].str[:4], data[0].str[4:]
  data['temp1']=data[1]
  data['year2'], data['month2'] = data[2].str[:4], data[2].str[4:]
  data['temp2']=data[3]
  data=data.drop([0,1,2,3],axis=1)
  #changing datatype from string to integer
  data['year1']=data['year1'].astype("int64")
  data['year2']=data['year2'].astype("int64")
  data['month1']=data['month1'].astype("int64")
  data['month2']=data['month2'].astype("int64")
  data['temp1']=data['temp1'].astype("int64")
  data['temp2']=data['temp2'].astype("int64")
  return data

df=dataclean(df)
df.head()

# takes the cleaned file and return it after splitting into two
def datasplit(data):
  data1=data.iloc[:500]
  data2=data.iloc[500:]
  return data1, data2

df1,df2=datasplit(df)
df1.head()

# creates key value pair of year and maximum temperature
def datamap (data):
  d1_1=data.groupby('year1').agg({"temp1":"max"}).reset_index().rename(columns={"temp1":"Max temp","year1":"year"})
  d1_2=data.groupby('year2').agg({"temp2":"max"}).reset_index().rename(columns={"temp2":"Max temp","year2":"year"})
  return d1_1,d1_2

df1_1,df1_2=datamap(df1)
df2_1,df2_2=datamap(df2)
df1_1.head()

# join all the dataframes and sort by year
def datasort(d1_1,d1_2,d2_1,d2_2):
  d_all=pd.concat([d1_1,d1_2,d2_1,d2_2],axis=0)
  d_all=d_all.sort_values('year',ascending=True)
  return d_all

df_all=datasort(df1_1,df1_2,df2_1,df2_2)
df_all.head()

# partition the data on year basis
def datapart(d_all):
  d_part1=d_all[d_all['year']<=2015]
  d_part2=d_all[d_all['year']>=2016]
  return d_part1,d_part2

df_part1,df_part2 =datapart(df_all)
df_part1.head()

# find the maximum of temperature by year
def datareduce(d_part):
  d_red=d_part.groupby('year').agg({"Max temp":max}).reset_index()
  return d_red

df_red1=datareduce(df_part1) 
df_red2=datareduce(df_part2) 
df_red1.head()

# combine all functions
def datamain():
  df=dataread()
  df=dataclean(df)
  df1,df2=datasplit(df)
  df1_1,df1_2=datamap(df1)
  df2_1,df2_2=datamap(df2)
  df_all=datasort(df1_1,df1_2,df2_1,df2_2)
  df_part1,df_part2 =datapart(df_all)
  df_red1=datareduce(df_part1)  
  df_red2=datareduce(df_part2)  
  df_final=pd.concat([df_red1,df_red2],axis=0).reset_index().drop('index',axis=1)
  return df_final

finalcsv=datamain()

finalcsv.to_csv("final_csv.csv",header=True)

